### ISSUE TITLE
 undefined symbol: GOMP_parallel

### ISSUE THREAD

**Issue by asegrenev** [benfred/implicit#13]
I've got some troubles with executing lastfm.py test:

asegrenev@vw:~/Downloads/implicit$ python3 examples/lastfm.py
Traceback (most recent call last):
  File "examples/lastfm.py", line 24, in <module>
    from implicit import alternating_least_squares
  File "/home/asegrenev/anaconda3/lib/python3.5/site-packages/implicit-0.1.7-py3.5-linux-x86_64.egg/implicit/__init__.py", line 1, in <module>
    from .implicit import alternating_least_squares
  File "/home/asegrenev/anaconda3/lib/python3.5/site-packages/implicit-0.1.7-py3.5-linux-x86_64.egg/implicit/implicit.py", line 6, in <module>
    from . import _implicit
ImportError: /home/asegrenev/anaconda3/lib/python3.5/site-packages/implicit-0.1.7-py3.5-linux-x86_64.egg/implicit/_implicit.cpython-35m-x86_64-linux-gnu.so: undefined symbol: GOMP_parallel

**Comment by benfred** [comment]
So, this might be an issue with anaconda and OpenMP, a similar issue was reported here: https://github.com/jupyter/docker-stacks/issues/177

According to that issue going 'conda install -y gcc' before installing implicit fixes. Can you try that?

**Comment by asegrenev** [comment]
Thank you!

**Comment by dheerajkumar-solanki** [comment]
Before installing implicit, I did "conda install -y gcc", but it showing the same error as previous:

>>> import implicit
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/sshuser/anaconda/lib/python2.7/site-packages/implicit/__init__.py", line 1, in <module>
    from .als import alternating_least_squares
  File "/home/sshuser/anaconda/lib/python2.7/site-packages/implicit/als.py", line 14, in <module>
    from . import _als
ImportError: /home/sshuser/anaconda/lib/python2.7/site-packages/implicit/_als.so: undefined symbol: GOMP_parallel
