### ISSUE TITLE
i am trying to install google assistant in my pc... i am very noob with python..please elp me out

### ISSUE THREAD

**Issue by akashpoddar56** [benfred/implicit#138]
Traceback (most recent call last):
      File "C:\Users\akash\AppData\Local\Programs\Python\Python37-32\lib\site-packages\setuptools\msvc.py", line 490, in _find_latest_available_vc_ver
        return self.find_available_vc_vers()[-1]
    IndexError: list index out of range

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "C:\Users\akash\AppData\Local\Temp\pip-install-umtya6g9\grpcio\src\python\grpcio\commands.py", line 292, in build_extensions
        build_ext.build_ext.build_extensions(self)
      File "C:\Users\akash\AppData\Local\Programs\Python\Python37-32\lib\distutils\command\build_ext.py", line 448, in build_extensions
        self._build_extensions_serial()
      File "C:\Users\akash\AppData\Local\Programs\Python\Python37-32\lib\distutils\command\build_ext.py", line 473, in _build_extensions_serial
        self.build_extension(ext)
      File "C:\Users\akash\AppData\Local\Programs\Python\Python37-32\lib\site-packages\setuptools\command\build_ext.py", line 199, in build_extension
        _build_ext.build_extension(self, ext)
      File "C:\Users\akash\AppData\Local\Programs\Python\Python37-32\lib\distutils\command\build_ext.py", line 533, in build_extension
        depends=ext.depends)
      File "C:\Users\akash\AppData\Local\Programs\Python\Python37-32\lib\distutils\_msvccompiler.py", line 345, in compile
        self.initialize()
      File "C:\Users\akash\AppData\Local\Programs\Python\Python37-32\lib\distutils\_msvccompiler.py", line 238, in initialize
        vc_env = _get_vc_env(plat_spec)
      File "C:\Users\akash\AppData\Local\Programs\Python\Python37-32\lib\site-packages\setuptools\msvc.py", line 185, in msvc14_get_vc_env
        return EnvironmentInfo(plat_spec, vc_min_ver=14.0).return_env()
      File "C:\Users\akash\AppData\Local\Programs\Python\Python37-32\lib\site-packages\setuptools\msvc.py", line 844, in __init__
        self.si = SystemInfo(self.ri, vc_ver)
      File "C:\Users\akash\AppData\Local\Programs\Python\Python37-32\lib\site-packages\setuptools\msvc.py", line 486, in __init__
        self.vc_ver = vc_ver or self._find_latest_available_vc_ver()
      File "C:\Users\akash\AppData\Local\Programs\Python\Python37-32\lib\site-packages\setuptools\msvc.py", line 493, in _find_latest_available_vc_ver
        raise distutils.errors.DistutilsPlatformError(err)
    distutils.errors.DistutilsPlatformError: Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual C++ Build Tools": http://landinghub.visualstudio.com/visual-cpp-build-tools

    ----------------------------------------
Command "C:\Users\akash\AppData\Local\Programs\Python\Python37-32\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\akash\\AppData\\Local\\Temp\\pip-install-umtya6g9\\grpcio\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\akash\AppData\Local\Temp\pip-record-nlh8_s9v\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in C:\Users\akash\AppData\Local\Temp\pip-install-umtya6g9\grpcio\

**Comment by benfred** [comment]
Steps to solve are here, https://github.com/benfred/implicit/issues/76#issuecomment-360872999
