### ISSUE TITLE
travis CI build error [numpy]

### ISSUE THREAD

**Issue by Tych0n** [benfred/implicit#180]
in Pull request #179, 

travis build failed for linux (3/3) and OSX (1/2) because of numpy import error.
travis log [#5.3](https://travis-ci.org/Tych0n/implicit/jobs/479827589#L663)

    // from line 662
    copying build/lib.linux-x86_64-3.6/implicit/evaluation.cpython-36m-x86_64-linux-gnu.so -> implicit
    Traceback (most recent call last):
      File "setup.py", line 163, in <module>
    ...
    // from line 698
      File "/home/travis/build/Tych0n/implicit/implicit/als.py", line 8, in <module>
        import numpy as np
      File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/numpy/__init__.py", line 142, in <module>
        from . import core
      File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/numpy/core/__init__.py", line 57, in <module>
        from . import numerictypes as nt
      File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/numpy/core/numerictypes.py", line 111, in <module>
        from ._type_aliases import (
      File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/numpy/core/_type_aliases.py", line 63, in <module>
        _concrete_types = {v.type for k, v in _concrete_typeinfo.items()}
      File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/numpy/core/_type_aliases.py", line 63, in <setcomp>
        _concrete_types = {v.type for k, v in _concrete_typeinfo.items()}
    AttributeError: 'tuple' object has no attribute 'type'

last successful travis build log [#333.3](https://travis-ci.org/benfred/implicit/jobs/404175032#L690) goes like

    // from line 690
    copying build/lib.linux-x86_64-3.6/implicit/evaluation.cpython-36m-x86_64-linux-gnu.so -> implicit
    test_dtype (tests.approximate_als_test.AnnoyALSTest) ... WARNING:root:OpenBLAS detected. Its highly recommend to set the environment variable 'export OPENBLAS_NUM_THREADS=1' to disable its internal multithreading
    ok
    test_evaluation (tests.approximate_als_test.AnnoyALSTest) ... ok
thanks

**Comment by Tych0n** [comment]
Fixed in https://github.com/benfred/implicit/pull/179/commits/3efb9aa654c9123ee189ab590134881bda3a0861

**Comment by ita9naiwa** [comment]
Thanks! I fixed the problem.
is it Okay to do it like this anyway? #213
