### ISSUE TITLE
ValueError: negative column index found

### ISSUE THREAD

**Issue by aravindhshn** [benfred/implicit#207]
Traceback (most recent call last):
  File "implict_file4.py", line 40, in <module>
    data['value'].astype(int))))
  File "/home/aravindh/anaconda3/lib/python3.6/site-packages/scipy/sparse/coo.py", line 192, in __init__
    self._check()
  File "/home/aravindh/anaconda3/lib/python3.6/site-packages/scipy/sparse/coo.py", line 278, in _check
    raise ValueError('negative column index found')
ValueError: negative column index found

**Comment by ita9naiwa** [comment]
check col, row when you build train matrix.

elements in col, row should be positive(because matrix indices must be so).
