### ISSUE TITLE
dlopen import error

### ISSUE THREAD

**Issue by xuezhaokun** [benfred/implicit#352]
I am running a Linux machine. I got the following error, when I tried to import implicit in my code. Any Idea? Thanks

Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 206, in fetch_command
    klass = load_command_class(app_name, subcommand)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 40, in load_command_class
    module = import_module('%s.management.commands.%s' % (app_name, name))
  File "/usr/local/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/hydroshare/hs_explore/management/commands/test_lda_pred_imp.py", line 31, in <module>
    import implicit
  File "/usr/local/lib/python3.6/site-packages/implicit/__init__.py", line 1, in <module>
    from . import als, approximate_als, bpr, lmf, nearest_neighbours
  File "/usr/local/lib/python3.6/site-packages/implicit/als.py", line 14, in <module>
    from . import _als
ImportError: dlopen: cannot load any more object with static TLS

**Comment by xuezhaokun** [comment]
It looks like that the library is not compatible with "import sklearn.cluster". After removing this library, it solved the problem. If I moved sklearn.cluster after importing implicit, it gives another import error.

**Comment by benfred** [comment]
This seems like its a glibc issue, that you can probably fix by upgrading your linux version:
https://github.com/pytorch/pytorch/issues/2575#issuecomment-523657178

Sorry can't help you more here,
