### ISSUE TITLE
matplotlib installation issue

### ISSUE THREAD

**Issue by KushalSharma19** [benfred/implicit#418]
C:\Users\kushal>pip install matplotlib
Collecting matplotlib
  Downloading matplotlib-3.3.2.tar.gz (37.9 MB)
     |████████████████████████████████| 37.9 MB 819 kB/s
Collecting certifi>=2020.06.20
  Using cached certifi-2020.6.20-py2.py3-none-any.whl (156 kB)
Collecting cycler>=0.10
  Downloading cycler-0.10.0-py2.py3-none-any.whl (6.5 kB)
Collecting kiwisolver>=1.0.1
  Downloading kiwisolver-1.2.0.tar.gz (52 kB)
     |████████████████████████████████| 52 kB 146 kB/s
    ERROR: Command errored out with exit status 1:
     command: 'c:\users\kushal\appdata\local\programs\python\python39\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\kushal\\AppData\\Local\\Temp\\pip-install-daxb8zvo\\kiwisolver\\setup.py'"'"'; __file__='"'"'C:\\Users\\kushal\\AppData\\Local\\Temp\\pip-install-daxb8zvo\\kiwisolver\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\kushal\AppData\Local\Temp\pip-pip-egg-info-hncp2ou5'
         cwd: C:\Users\kushal\AppData\Local\Temp\pip-install-daxb8zvo\kiwisolver\
    Complete output (44 lines):
    WARNING: The wheel package is not available.
      ERROR: Command errored out with exit status 1:
       command: 'c:\users\kushal\appdata\local\programs\python\python39\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\kushal\\AppData\\Local\\Temp\\pip-wheel-88eyt6l8\\cppy\\setup.py'"'"'; __file__='"'"'C:\\Users\\kushal\\AppData\\Local\\Temp\\pip-wheel-88eyt6l8\\cppy\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\kushal\AppData\Local\Temp\pip-wheel-76stexjj'
           cwd: C:\Users\kushal\AppData\Local\Temp\pip-wheel-88eyt6l8\cppy\
      Complete output (6 lines):
      usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
         or: setup.py --help [cmd1 cmd2 ...]
         or: setup.py --help-commands
         or: setup.py cmd --help

      error: invalid command 'bdist_wheel'
      ----------------------------------------
      ERROR: Failed building wheel for cppy
    ERROR: Failed to build one or more wheels
    Traceback (most recent call last):
      File "c:\users\kushal\appdata\local\programs\python\python39\lib\site-packages\setuptools\installer.py", line 128, in fetch_build_egg
        subprocess.check_call(cmd)
      File "c:\users\kushal\appdata\local\programs\python\python39\lib\subprocess.py", line 373, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['c:\\users\\kushal\\appdata\\local\\programs\\python\\python39\\python.exe', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', 'C:\\Users\\kushal\\AppData\\Local\\Temp\\tmp24fbsvl5', '--quiet', 'cppy>=1.1.0']' returned non-zero exit status 1.

    The above exception was the direct cause of the following exception:

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\kushal\AppData\Local\Temp\pip-install-daxb8zvo\kiwisolver\setup.py", line 59, in <module>
        setup(
      File "c:\users\kushal\appdata\local\programs\python\python39\lib\site-packages\setuptools\__init__.py", line 164, in setup
        _install_setup_requires(attrs)
      File "c:\users\kushal\appdata\local\programs\python\python39\lib\site-packages\setuptools\__init__.py", line 159, in _install_setup_requires
        dist.fetch_build_eggs(dist.setup_requires)
      File "c:\users\kushal\appdata\local\programs\python\python39\lib\site-packages\setuptools\dist.py", line 699, in fetch_build_eggs
        resolved_dists = pkg_resources.working_set.resolve(
      File "c:\users\kushal\appdata\local\programs\python\python39\lib\site-packages\pkg_resources\__init__.py", line 779, in resolve
        dist = best[req.key] = env.best_match(
      File "c:\users\kushal\appdata\local\programs\python\python39\lib\site-packages\pkg_resources\__init__.py", line 1064, in best_match
        return self.obtain(req, installer)
      File "c:\users\kushal\appdata\local\programs\python\python39\lib\site-packages\pkg_resources\__init__.py", line 1076, in obtain
        return installer(requirement)
      File "c:\users\kushal\appdata\local\programs\python\python39\lib\site-packages\setuptools\dist.py", line 758, in fetch_build_egg
        return fetch_build_egg(self, req)
      File "c:\users\kushal\appdata\local\programs\python\python39\lib\site-packages\setuptools\installer.py", line 130, in fetch_build_egg
        raise DistutilsError(str(e)) from e
    distutils.errors.DistutilsError: Command '['c:\\users\\kushal\\appdata\\local\\programs\\python\\python39\\python.exe', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', 'C:\\Users\\kushal\\AppData\\Local\\Temp\\tmp24fbsvl5', '--quiet', 'cppy>=1.1.0']' returned non-zero exit status 1.
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by KushalSharma19** [comment]
hello, ben why did you close. I didn't write anything wrong. I just asked the solution of the error while installing matplotlib. 
If did anything wrong then please tell me about my mistake and i am really sorry if i did something wrong.

**Comment by ita9naiwa** [comment]
@KushalSharma19 It's an issue page on this library, not matplotlib.
better check here https://github.com/matplotlib/matplotlib/issues

**Comment by KushalSharma19** [comment]
Can you tell me how to solve this issue? 
Any command or something.
