### ISSUE TITLE
Running on Kaggle GPU

### ISSUE THREAD

**Issue by mattiasu96** [benfred/implicit#438]
Is there a way to run the ALS algorithm on kaggle using their GPU? 

I added the field "use_gpu=True" but i get the following error: 
```

[W 2020-12-24 21:49:54,144] Trial 0 failed because of the following error: ValueError("No CUDA extension has been built, can't train on GPU.")
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/optuna/_optimize.py", line 189, in _run_trial
    value = func(trial)
  File "<ipython-input-8-43b7fb89dea1>", line 19, in __call__
    recommender.fit(n_factors = n_factors, regularization = regularization, iterations = iterations)
  File "/kaggle/working/MatrixFactorization/IALSRecommender_implicit.py", line 48, in fit
    model.fit(data_conf)
  File "/opt/conda/lib/python3.7/site-packages/implicit/als.py", line 163, in fit
    return self._fit_gpu(Ciu, Cui, show_progress)
  File "/opt/conda/lib/python3.7/site-packages/implicit/als.py", line 194, in _fit_gpu
    raise ValueError("No CUDA extension has been built, can't train on GPU.")
ValueError: No CUDA extension has been built, can't train on GPU.
```

**Comment by benfred** [comment]
How did you install implicit? If you installed from conda - did you select the GPU version? (```conda install -c conda-forge implicit implicit-proc=*=gpu```)

**Comment by mattiasu96** [comment]
In the end I switched to Colab, so I haven't tried it anymore on Kaggle
