### ISSUE TITLE
Error installing implicit on Ubuntu

### ISSUE THREAD

**Issue by rowanv** [benfred/implicit#57]
Hey, thanks for putting together this package. I'm encountering a C compiling-related error when I try to install it on Ubuntu. I've checked that gcc is installed. Any thoughts on what might be going on?

Thanks,

```
Collecting implicit==0.2.6 (from -r requirements.txt (line 67))
Downloading implicit-0.2.6.tar.gz (260kB)

    100% || 266kB 2.6MB/s 
plete output from command python setup.py egg_info:

Error compiling Cython file:
------------------------------------------------------------
...
from cython.parallel import parallel, prange
from libc.stdlib cimport malloc, free
from libc.string cimport memcpy

# requires scipy v0.16
cimport scipy.linalg.cython_lapack as cython_lapack
^
------------------------------------------------------------

implicit/_als.pyx:9:8: 'scipy/linalg/cython_lapack.pxd' not found

Error compiling Cython file:
------------------------------------------------------------
...
from libc.stdlib cimport malloc, free
from libc.string cimport memcpy

# requires scipy v0.16
cimport scipy.linalg.cython_lapack as cython_lapack
cimport scipy.linalg.cython_blas as cython_blas
^
------------------------------------------------------------

implicit/_als.pyx:10:8: 'scipy/linalg/cython_blas.pxd' not found

Error compiling Cython file:
------------------------------------------------------------
...
cdef inline void axpy(int * n, floating * da, floating * dx, int * incx, floating * dy,
int * incy) nogil:
if floating is double:
cython_blas.daxpy(n, da, dx, incx, dy, incy)
else:
cython_blas.saxpy(n, da, dx, incx, dy, incy)
^
------------------------------------------------------------

implicit/_als.pyx:18:19: cimported module has no attribute 'saxpy'

Error compiling Cython file:
------------------------------------------------------------
...

# lapack/blas wrappers for cython fused types
cdef inline void axpy(int * n, floating * da, floating * dx, int * incx, floating * dy,
int * incy) nogil:
if floating is double:
cython_blas.daxpy(n, da, dx, incx, dy, incy)
^
------------------------------------------------------------

implicit/_als.pyx:16:19: cimported module has no attribute 'daxpy'

Error compiling Cython file:
------------------------------------------------------------
...
cdef inline void symv(char *uplo, int *n, floating *alpha, floating *a, int *lda, floating *x,
int *incx, floating *beta, floating *y, int *incy) nogil:
if floating is double:
cython_blas.dsymv(uplo, n, alpha, a, lda, x, incx, beta, y, incy)
else:
cython_blas.ssymv(uplo, n, alpha, a, lda, x, incx, beta, y, incy)
^
------------------------------------------------------------

implicit/_als.pyx:25:19: cimported module has no attribute 'ssymv'

Error compiling Cython file:
------------------------------------------------------------
...
cython_blas.saxpy(n, da, dx, incx, dy, incy)

cdef inline void symv(char *uplo, int *n, floating *alpha, floating *a, int *lda, floating *x,
int *incx, floating *beta, floating *y, int *incy) nogil:
if floating is double:
cython_blas.dsymv(uplo, n, alpha, a, lda, x, incx, beta, y, incy)
^
------------------------------------------------------------

implicit/_als.pyx:23:19: cimported module has no attribute 'dsymv'

Error compiling Cython file:
------------------------------------------------------------
...

cdef inline floating dot(int *n, floating *sx, int *incx, floating *sy, int *incy) nogil:
if floating is double:
return cython_blas.ddot(n, sx, incx, sy, incy)
else:
return cython_blas.sdot(n, sx, incx, sy, incy)
^
------------------------------------------------------------

implicit/_als.pyx:31:26: cimported module has no attribute 'sdot'

Error compiling Cython file:
------------------------------------------------------------
...
else:
cython_blas.ssymv(uplo, n, alpha, a, lda, x, incx, beta, y, incy)

cdef inline floating dot(int *n, floating *sx, int *incx, floating *sy, int *incy) nogil:
if floating is double:
return cython_blas.ddot(n, sx, incx, sy, incy)
^
------------------------------------------------------------

implicit/_als.pyx:29:26: cimported module has no attribute 'ddot'

Error compiling Cython file:
------------------------------------------------------------
...

cdef inline void scal(int *n, floating *sa, floating *sx, int *incx) nogil:
if floating is double:
cython_blas.dscal(n, sa, sx, incx)
else:
cython_blas.sscal(n, sa, sx, incx)
^
------------------------------------------------------------

implicit/_als.pyx:37:19: cimported module has no attribute 'sscal'

Error compiling Cython file:
------------------------------------------------------------
...
else:
return cython_blas.sdot(n, sx, incx, sy, incy)

cdef inline void scal(int *n, floating *sa, floating *sx, int *incx) nogil:
if floating is double:
cython_blas.dscal(n, sa, sx, incx)
^
------------------------------------------------------------

implicit/_als.pyx:35:19: cimported module has no attribute 'dscal'

Error compiling Cython file:
------------------------------------------------------------
...
cdef inline void posv(char * u, int * n, int * nrhs, floating * a, int * lda, floating * b,
int * ldb, int * info) nogil:
if floating is double:
cython_lapack.dposv(u, n, nrhs, a, lda, b, ldb, info)
else:
cython_lapack.sposv(u, n, nrhs, a, lda, b, ldb, info)
^
------------------------------------------------------------

implicit/_als.pyx:44:21: cimported module has no attribute 'sposv'

Error compiling Cython file:
------------------------------------------------------------
...
cython_blas.sscal(n, sa, sx, incx)

cdef inline void posv(char * u, int * n, int * nrhs, floating * a, int * lda, floating * b,
int * ldb, int * info) nogil:
if floating is double:
cython_lapack.dposv(u, n, nrhs, a, lda, b, ldb, info)
^
------------------------------------------------------------

implicit/_als.pyx:42:21: cimported module has no attribute 'dposv'

Error compiling Cython file:
------------------------------------------------------------
...
cdef inline void gesv(int * n, int * nrhs, floating * a, int * lda, int * piv, floating * b,
int * ldb, int * info) nogil:
if floating is double:
cython_lapack.dgesv(n, nrhs, a, lda, piv, b, ldb, info)
else:
cython_lapack.sgesv(n, nrhs, a, lda, piv, b, ldb, info)
^
------------------------------------------------------------

implicit/_als.pyx:51:21: cimported module has no attribute 'sgesv'

Error compiling Cython file:
------------------------------------------------------------
...
cython_lapack.sposv(u, n, nrhs, a, lda, b, ldb, info)

cdef inline void gesv(int * n, int * nrhs, floating * a, int * lda, int * piv, floating * b,
int * ldb, int * info) nogil:
if floating is double:
cython_lapack.dgesv(n, nrhs, a, lda, piv, b, ldb, info)
^
------------------------------------------------------------

implicit/_als.pyx:49:21: cimported module has no attribute 'dgesv'

Error compiling Cython file:
------------------------------------------------------------
...
cdef inline void axpy(int * n, floating * da, floating * dx, int * incx, floating * dy,
int * incy) nogil:
if floating is double:
cython_blas.daxpy(n, da, dx, incx, dy, incy)
else:
cython_blas.saxpy(n, da, dx, incx, dy, incy)
^
------------------------------------------------------------

implicit/_als.pyx:18:25: Calling gil-requiring function not allowed without gil

Error compiling Cython file:
------------------------------------------------------------
...

# lapack/blas wrappers for cython fused types
cdef inline void axpy(int * n, floating * da, floating * dx, int * incx, floating * dy,
int * incy) nogil:
if floating is double:
cython_blas.daxpy(n, da, dx, incx, dy, incy)
^
------------------------------------------------------------

implicit/_als.pyx:16:25: Calling gil-requiring function not allowed without gil

Error compiling Cython file:
------------------------------------------------------------
...
cdef inline void symv(char *uplo, int *n, floating *alpha, floating *a, int *lda, floating *x,
int *incx, floating *beta, floating *y, int *incy) nogil:
if floating is double:
cython_blas.dsymv(uplo, n, alpha, a, lda, x, incx, beta, y, incy)
else:
cython_blas.ssymv(uplo, n, alpha, a, lda, x, incx, beta, y, incy)
^
------------------------------------------------------------

implicit/_als.pyx:25:25: Calling gil-requiring function not allowed without gil

Error compiling Cython file:
------------------------------------------------------------
...
cython_blas.saxpy(n, da, dx, incx, dy, incy)

cdef inline void symv(char *uplo, int *n, floating *alpha, floating *a, int *lda, floating *x,
int *incx, floating *beta, floating *y, int *incy) nogil:
if floating is double:
cython_blas.dsymv(uplo, n, alpha, a, lda, x, incx, beta, y, incy)
^
------------------------------------------------------------

implicit/_als.pyx:23:25: Calling gil-requiring function not allowed without gil

Error compiling Cython file:
------------------------------------------------------------
...

cdef inline floating dot(int *n, floating *sx, int *incx, floating *sy, int *incy) nogil:
if floating is double:
return cython_blas.ddot(n, sx, incx, sy, incy)
else:
return cython_blas.sdot(n, sx, incx, sy, incy)
^
------------------------------------------------------------

implicit/_als.pyx:31:31: Calling gil-requiring function not allowed without gil

Error compiling Cython file:
------------------------------------------------------------
...
else:
cython_blas.ssymv(uplo, n, alpha, a, lda, x, incx, beta, y, incy)

cdef inline floating dot(int *n, floating *sx, int *incx, floating *sy, int *incy) nogil:
if floating is double:
return cython_blas.ddot(n, sx, incx, sy, incy)
^
------------------------------------------------------------

implicit/_als.pyx:29:31: Calling gil-requiring function not allowed without gil

Error compiling Cython file:
------------------------------------------------------------
...

cdef inline void scal(int *n, floating *sa, floating *sx, int *incx) nogil:
if floating is double:
cython_blas.dscal(n, sa, sx, incx)
else:
cython_blas.sscal(n, sa, sx, incx)
^
------------------------------------------------------------

implicit/_als.pyx:37:25: Calling gil-requiring function not allowed without gil

Error compiling Cython file:
------------------------------------------------------------
...
else:
return cython_blas.sdot(n, sx, incx, sy, incy)

cdef inline void scal(int *n, floating *sa, floating *sx, int *incx) nogil:
if floating is double:
cython_blas.dscal(n, sa, sx, incx)
^
------------------------------------------------------------

implicit/_als.pyx:35:25: Calling gil-requiring function not allowed without gil

Error compiling Cython file:
------------------------------------------------------------
...
cdef inline void posv(char * u, int * n, int * nrhs, floating * a, int * lda, floating * b,
int * ldb, int * info) nogil:
if floating is double:
cython_lapack.dposv(u, n, nrhs, a, lda, b, ldb, info)
else:
cython_lapack.sposv(u, n, nrhs, a, lda, b, ldb, info)
^
------------------------------------------------------------

implicit/_als.pyx:44:27: Calling gil-requiring function not allowed without gil

Error compiling Cython file:
------------------------------------------------------------
...
cython_blas.sscal(n, sa, sx, incx)

cdef inline void posv(char * u, int * n, int * nrhs, floating * a, int * lda, floating * b,
int * ldb, int * info) nogil:
if floating is double:
cython_lapack.dposv(u, n, nrhs, a, lda, b, ldb, info)
^
------------------------------------------------------------

implicit/_als.pyx:42:27: Calling gil-requiring function not allowed without gil

Error compiling Cython file:
------------------------------------------------------------
...
cdef inline void gesv(int * n, int * nrhs, floating * a, int * lda, int * piv, floating * b,
int * ldb, int * info) nogil:
if floating is double:
cython_lapack.dgesv(n, nrhs, a, lda, piv, b, ldb, info)
else:
cython_lapack.sgesv(n, nrhs, a, lda, piv, b, ldb, info)
^
------------------------------------------------------------

implicit/_als.pyx:51:27: Calling gil-requiring function not allowed without gil

Error compiling Cython file:
------------------------------------------------------------
...
cython_lapack.sposv(u, n, nrhs, a, lda, b, ldb, info)

cdef inline void gesv(int * n, int * nrhs, floating * a, int * lda, int * piv, floating * b,
int * ldb, int * info) nogil:
if floating is double:
cython_lapack.dgesv(n, nrhs, a, lda, piv, b, ldb, info)
^
------------------------------------------------------------

implicit/_als.pyx:49:27: Calling gil-requiring function not allowed without gil
Traceback (most recent call last):
File "<string>", line 1, in <module>
File "/tmp/pip-build-5s7y1gnq/implicit/setup.py", line 111, in <module>
ext_modules=define_extensions(use_cython),
File "/tmp/pip-build-5s7y1gnq/implicit/setup.py", line 47, in define_extensions
return cythonize(modules)
File "/home/rof/.pyenv/versions/3.5.4/lib/python3.5/site-packages/Cython/Build/Dependencies.py", line 1039, in cythonize
cythonize_one(*args)
File "/home/rof/.pyenv/versions/3.5.4/lib/python3.5/site-packages/Cython/Build/Dependencies.py", line 1161, in cythonize_one
raise CompileError(None, pyx_file)
Cython.Compiler.Errors.CompileError: implicit/_als.pyx
implicit/_als.pyx: cannot find cimported module 'scipy.linalg.cython_lapack'
implicit/_als.pyx: cannot find cimported module 'scipy.linalg.cython_blas'
Compiling implicit/_als.pyx because it depends on /home/rof/.pyenv/versions/3.5.4/lib/python3.5/site-packages/Cython/Includes/libc/string.pxd.
Compiling implicit/_nearest_neighbours.pyx because it depends on /home/rof/.pyenv/versions/3.5.4/lib/python3.5/site-packages/Cython/Includes/libcpp/vector.pxd.
[1/2] Cythonizing implicit/_als.pyx

----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-5s7y1gnq/implicit/
```

**Comment by benfred** [comment]
What version of scipy are you using? I think these functions were added in v0.16

**Comment by rowanv** [comment]
`scipy==0.19.1`.

The same requirements set worked on Mac OS X 10.12.14, if that helps, this is an error that I encountered when pushing out to the CI server.

**Comment by benfred** [comment]
Interesting. I'm using ubuntu w/ scipy v 0.19.0 (via the python3 anaconda distribution) without any issues myself.

Can you verify that the 'cython_lapack.pxd' file is included in the scipy thats getting picked up?

```
python -c "import scipy.linalg; import os; dirname = os.path.dirname(scipy.linalg.__file__); print(dirname); print(scipy.__version__); print('\n'.join(os.listdir(dirname)))"
```

**Comment by rowanv** [comment]
Hmm you know, I think this might actually be an issue with the CI service provider. I've tried ssh-ing into their CI boxes and doing a manual install of all packages, and can't replicate the error. Have also tried deploying to my own Ubuntu box, and I can't replicate the error. It only seems to happen when the CI service runs the dependency installation as part of their installation chain, so I'm going to assume that something odd is going on on their end.

**Comment by rowanv** [comment]
Ok, managed to replicate the error. For some reason, if I install the components manually, i.e.

`pip install Cython==0.27.2`
`pip install scipy==0.19.1`
`pip install implicit==0.2.6`
and then
`pip install -r requirements.txt` for the rest of my requirements

that succeeds on Ubuntu 14.04.

However, moving scipy and implicit into the `requirements.txt` file results in a failure. As far as I can tell, there shouldn't be a reason that the two are different, since the `requirements.txt` file output shows that the right package versions are installed or cached:

```
Collecting scipy==0.19.1 (from -r requirements.txt (line 69))
  Using cached scipy-0.19.1-cp35-cp35m-manylinux1_x86_64.whl
Collecting implicit==0.2.6 (from -r requirements.txt (line 70))
  Using cached implicit-0.2.6.tar.gz
    Complete output from command python setup.py egg_info:
    
    Error compiling Cython file:
    ------------------------------------------------------------
    ...
```

and yet I still get that odd error that suggests that it's using the wrong version of scipy. No idea why this might be happening since all of the versions are pegged, but installing outside of `requirements.txt` works fine for now.

**Comment by benfred** [comment]
interesting - I think it must be picking up the wrong version somehow =( glad you managed to work around this problem!

**Comment by erseema** [comment]
HI, I am using implicit to implement ALS . While fitting model, I am getting error "AttributeError: 'DataFrame' object has no attribute 'tocsr'" 
Using scipy version 0.16 
implicit version - 0.2.7

**Comment by benfred** [comment]
@erseema That looks like you're passing a pandas dataframe to the fit function, when you should be passing a sparse matrix (like a scipy.sparse.csr_matrix or similar) in. 

Check out the examples for how to convert: https://github.com/benfred/implicit/blob/master/examples/lastfm.py#L71

**Comment by guilhermeparreira** [comment]
Hi, can you provide an example of how you suggest to convert a pandas dataframe to sparse matrix?

I did not understand the link you provided.

I tried this one:
https://hippocampus-garden.com/pandas_sparse/#:~:text=To%20convert%20a%20DataFrame%20to,a%20coordinate%20(COO)%20matrix.

which worked, but I don't know if this is the best way..
