### ISSUE TITLE
pip install implicit is not work to use GPU

### ISSUE THREAD

**Issue by RYT09** [benfred/implicit#699]
The command "pip install implicit" does not install the necessary GPU extensions, resulting in an error:
(implicit) production-cuda-server:/data$ python implicit_test.py
/home/xingyuan/anaconda3/envs/implicit/lib/python3.10/site-packages/implicit/cpu/als.py:95: RuntimeWarning: OpenBLAS is configured to use 6 threads. It is highly recommended to disable its internal threadpool by setting the environment variable 'OPENBLAS_NUM_THREADS=1' or by calling 'threadpoolctl.threadpool_limits(1, "blas")'. Having OpenBLAS use a threadpool can lead to severe performance issues here.
  check_blas_config()
<class 'implicit.cpu.als.AlternatingLeastSquares'>
Traceback (most recent call last):
  File "/data/implicit_test.py", line 21, in <module>
    model = model.to_gpu()
  File "/home/anaconda3/envs/implicit/lib/python3.10/site-packages/implicit/cpu/als.py", line 442, in to_gpu
    ret = implicit.gpu.als.AlternatingLeastSquares(
  File "/home/anaconda3/envs/implicit/lib/python3.10/site-packages/implicit/gpu/als.py", line 59, in __init__
    raise ValueError("No CUDA extension has been built, can't train on GPU.")
ValueError: No CUDA extension has been built, can't train on GPU.

To enable GPU inference and training, it is required to use "conda install -c conda-forge implicit implicit-proc=*=gpu". How can I resolve this issue? I need to use pip installing the package

**Comment by RYT09** [comment]
This is my implicit and python version
implicit Version: 0.7.2
python Version：3.10
CUDA Version: 12.2

**Comment by RYT09** [comment]
Thank you so much for your help! Your solution indeed resolved my issue.
